#!/bin/bash
#SBATCH -N 1
#SBATCH -t 48:00:00
#SBATCH -p normal

python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__675 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__676 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__677 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__678 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__679 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__680 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__681 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__682 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__683 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__684 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__685 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__686 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__687 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__688 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__689 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__690 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__691 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__692 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__693 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__694 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__695 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__696 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__697 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__698 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__699 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__700 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__701 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__702 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__703 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__704 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__705 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__706 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__707 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__708 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__709 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__710 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__711 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__712 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__713 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__714 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__715 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__716 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__717 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__718 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__719 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__720 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__721 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__722 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__723 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__724 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__725 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__726 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__727 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__728 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__729 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__730 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__731 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__732 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__733 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__734 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__735 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__736 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__737 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__738 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__739 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__740 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__741 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__742 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__743 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__744 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__745 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__746 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__747 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__748 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__749 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__750 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__751 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__752 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__753 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__754 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__755 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__756 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__757 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__758 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__759 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__760 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__761 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__762 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__763 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__764 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__765 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__766 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__767 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__768 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__769 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__770 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__771 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__772 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__773 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__774 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__775 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__776 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__777 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__778 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__779 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__780 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__781 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__782 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__783 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__784 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__785 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__786 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__787 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__788 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__789 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__790 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__791 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__792 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__793 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__794 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__795 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__796 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__797 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__798 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__799 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__800 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__801 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__802 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__803 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__804 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__805 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__806 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__807 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__808 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__809 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__810 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__811 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__812 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__813 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__814 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__815 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__816 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__817 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__818 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__819 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__820 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__821 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__822 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__823 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__824 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__825 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__826 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__827 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__828 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__829 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__830 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__831 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__832 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__833 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__834 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__835 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__836 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__837 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__838 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__839 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__840 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__841 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__842 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__843 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__844 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__845 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__846 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__847 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__848 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__849 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__850 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__851 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__852 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__853 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__854 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__855 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__856 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__857 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__858 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__859 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__860 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__861 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__862 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__863 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__864 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__865 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__866 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__867 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__868 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__869 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__870 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__871 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__872 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__873 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__874 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__875 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__876 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__877 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__878 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__879 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__880 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__881 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__882 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__883 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__884 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__885 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__886 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__887 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__888 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__889 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__890 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__891 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__892 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__893 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__894 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__895 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__896 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__897 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__898 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__899 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__900 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__901 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__902 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__903 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__904 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__905 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__906 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__907 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__908 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__909 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__910 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__911 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__912 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__913 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__914 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__915 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__916 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__917 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__918 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__919 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__920 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__921 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__922 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__923 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__924 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__925 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__926 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__927 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__928 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__929 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__930 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__931 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__932 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__933 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__934 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__935 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__936 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__937 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__938 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__939 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__940 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__941 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__942 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__943 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__944 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__945 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__946 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__947 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__948 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__949 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__950 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__951 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__952 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__953 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__954 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__955 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__956 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__957 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__958 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__959 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__960 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__961 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__962 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__963 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__964 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__965 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__966 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__967 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__968 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__969 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__970 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__971 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__972 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__973 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__974 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__975 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__976 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__977 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__978 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__979 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__980 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__981 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__982 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__983 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__984 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__985 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__986 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__987 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__988 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__989 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__990 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__991 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__992 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__993 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__994 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__995 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__996 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__997 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__998 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__999 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1000 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1001 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1002 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1003 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1004 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1005 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1006 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1007 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1008 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1009 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1010 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1011 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1012 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1013 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1014 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1015 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1016 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1017 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1018 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1019 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1020 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1021 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1022 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1023 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1024 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1025 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1026 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1027 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1028 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1029 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1030 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1031 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1032 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1033 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1034 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1035 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1036 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1037 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1038 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1039 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1040 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1041 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1042 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1043 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1044 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1045 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1046 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1047 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1048 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1049 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1050 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1051 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1052 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1053 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1054 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1055 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1056 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1057 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1058 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1059 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1060 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1061 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1062 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1063 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1064 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1065 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1066 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1067 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1068 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1069 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1070 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1071 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1072 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1073 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1074 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1075 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1076 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1077 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1078 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1079 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1080 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1081 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1082 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1083 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1084 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1085 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1086 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1087 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1088 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1089 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1090 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1091 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1092 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1093 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1094 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1095 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1096 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1097 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1098 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1099 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1100 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1101 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1102 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1103 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1104 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1105 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1106 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1107 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1108 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1109 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1110 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1111 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1112 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1113 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1114 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1115 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1116 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1117 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1118 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1119 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1120 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1121 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1122 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1123 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1124 calibration &
wait

